#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	ACTMONHPBARSCRIPT,
	ARENABGMSCRIPT,
	ATTACKNUMSCRIPT,
	BAGSLOT0SCRIPT,
	BAGSLOT1SCRIPT,
	BIGCOSTSCRIPT,
	BLOODEFFECTSCRIPT,
	CARDATTACKSCRIPT,
	CARDATTNUMSCRIPT,
	CARDCOSTNUMSCRIPT,
	CARDDEFFENCESCRIPT,
	CARDDEFNUMSCRIPT,
	CARDMGRSCRIPT,
	CARDMOVESCRIPT,
	CARDSCRIPT,
	CHALLENGERSCRIPT,
	CHARGESCRIPT,
	CROSSBOWSCRIPT,
	DEMONDOGSCRIPT,
	DISCARDPILESCRIPT,
	DRAWHANDCNTSCRIPT,
	DRAWPILESCRIPT,
	ENDINGSOUNDSCRIPT,
	EXHASUSPILESCRIPT,
	FASTSCRIPT,
	GAMEMGRSCRIPT,
	HANDCARDLIMITSCRIPT,
	HITEFFECTSCRIPT,
	HPPOTIONSCRIPT,
	ICARDATTNUMSCRIPT,
	ICARDDEFNUMSCRIPT,
	ICEREAPERSCRIPT,
	ITEMCARDSCRIPT,
	LEFTWAPONSLOTSCRIPT,
	LV0MONSPAWNSCRIPT,
	LV1MONSPAWNSCRIPT,
	LVCHANGER0SCRIPT,
	LVCHANGER1SCRIPT,
	MAINBGMSCRIPT,
	MISSILESCRIPT,
	MOUSECHECKSCRIPT,
	NORMALKATANASCRIPT,
	NUMBERSCRIPT,
	OLDSHIELDSCRIPT,
	OLDSWORDSCRIPT,
	PERSONFBASE0SCRIPT,
	PLAYERHANDSCRIPT,
	PLAYERHPBARSCRIPT,
	PLAYERHPSCRIPT,
	PLAYERLEFTHANDSCRIPT,
	PLAYERRIGHTHANDSCRIPT,
	PLAYERSCRIPT,
	PLAYERSHIELDSCRIPT,
	REFBEETLESCRIPT,
	RIGHTWAPONSLOTSCRIPT,
	SHIELDNUMSCRIPT,
	STARTBTNSCRIPT,
	STDATTACKEFFSCRIPT,
	STDPARTICLESCRIPT,
	TILEMGRSCRIPT,
	TILESCRIPT,
	TLV0MONSPAWNSCRIPT,
	TLV1MONSPAWNSCRIPT,
	TLV2MONSPAWNSCRIPT,
	TLV3MONSPAWNSCRIPT,
	TLV4MONSPAWNSCRIPT,
	TLV5MONSPAWNSCRIPT,
	TURNENDBTNSCRIPT,
	UIMGRSCRIPT,
	UNDERATTACKSCRIPT,
	WINLOGOSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
